version: 0.2
phases:
  build:
    commands:
      - mkdir -p build
      - cp -r MapData ./build
      - cd ./build/MapData
      - sbt assembly
artifacts:
  files:
    - ./build/MapData/target/scala-2.12/mapData.jar
    - ./build/MapData/serverless.yml
  name: mapDataApplication
  discard-paths: yes
