version: 0.2
phases:
  build:
    commands:
      - mkdir -p build
      - cp -r MapData ./build
      - cd ./build/MapData
      - sbt assembly
      - sbt test
      - npm install -g serverless
      - serverless package --package my-artifacts
artifacts:
  files:
    - ./build/MapData/target/scala-2.12/mapData.jar
    - ./build/MapData/serverless.yml
    - ./build/MapData/my-artifacts/cloudformation-template-update-stack.json
    - ./build/MapData/my-artifacts/cloudformation-template-create-stack.json
    - ./build/MapData/my-artifacts/serverless-state.json
  name: mapDataApplication
  discard-paths: yes
